name: Tests
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: pip install uv

    - name: Style check
      uses: chartboost/ruff-action@v1

    - name: Check types
      run: uv run mypy .

    - name: Run tests
      run: uv run pytest -v
      env:
        PODBUCKET_POD_TOKEN: ${{ secrets.PODBUCKET_POD_TOKEN }}
